setGeneric("se.exprs", function(object) standardGeneric("se.exprs"))
setGeneric("weights", function(object) standardGeneric("weights"))
setGeneric("residuals", function(object) standardGeneric("residuals"))
setGeneric("randomeffects", function(object) standardGeneric("randomeffects"))
setGeneric("as.ExpressionSet", function(object) standardGeneric("as.ExpressionSet"))
